name: fiumicello_frontend
description: Frontend financiero Fiumicello (gastos y consultas)
publish_to: none
version: 0.8.5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_fiumicello.png
    - assets/logo_fiumicello_blanco.png
    - assets/gorro_fiumicello.png